export const learningIndustries = [
  { id: "general", label: { ru: "Универсально", en: "General" } },
  { id: "retail", label: { ru: "Ритейл и e-commerce", en: "Retail and e-commerce" } },
  { id: "services", label: { ru: "Услуги и клиентский сервис", en: "Services and customer support" } },
  { id: "education", label: { ru: "Образование", en: "Education" } },
  { id: "marketing", label: { ru: "Маркетинг и медиа", en: "Marketing and media" } },
  { id: "hr", label: { ru: "HR и рекрутинг", en: "HR and recruiting" } },
  { id: "operations", label: { ru: "Операции и управление", en: "Operations and management" } },
];

export const learningRoles = [
  { id: "owner", label: { ru: "Собственник / директор", en: "Owner / director" } },
  { id: "manager", label: { ru: "Менеджер", en: "Manager" } },
  { id: "marketer", label: { ru: "Маркетолог / SMM", en: "Marketer / SMM" } },
  { id: "sales", label: { ru: "Продажи", en: "Sales" } },
  { id: "hr", label: { ru: "HR / рекрутер", en: "HR / recruiter" } },
  { id: "analyst", label: { ru: "Аналитик", en: "Analyst" } },
  { id: "teacher", label: { ru: "Преподаватель / методист", en: "Teacher / methodologist" } },
  { id: "specialist", label: { ru: "Специалист", en: "Specialist" } },
];

export const learningAgeGroups = [
  { id: "kids", label: { ru: "8-12 лет", en: "8-12 years" } },
  { id: "teens", label: { ru: "13-17 лет", en: "13-17 years" } },
  { id: "young", label: { ru: "18-29 лет", en: "18-29 years" } },
  { id: "adults", label: { ru: "30+ лет", en: "30+ years" } },
];

export const learningLevels = [
  { id: "beginner", label: { ru: "Новичок", en: "Beginner" } },
  { id: "intermediate", label: { ru: "Уже пользуюсь AI", en: "Already using AI" } },
  { id: "advanced", label: { ru: "Продвинутый", en: "Advanced" } },
];

export const learningFormats = [
  { id: "text", label: { ru: "Текст", en: "Text" } },
  { id: "voice", label: { ru: "Голос", en: "Voice" } },
  { id: "hybrid", label: { ru: "Текст + голос", en: "Text + voice" } },
];

export const learningGoals = [
  { id: "productivity", label: { ru: "Экономия времени", en: "Time savings" } },
  { id: "quality", label: { ru: "Качество результата", en: "Quality improvements" } },
  { id: "automation", label: { ru: "Автоматизация рутины", en: "Automation" } },
  { id: "content", label: { ru: "Контент и маркетинг", en: "Content and marketing" } },
  { id: "sales", label: { ru: "Рост продаж", en: "Sales growth" } },
  { id: "training", label: { ru: "Обучение команды", en: "Team training" } },
];

export const learningModules = [
  {
    id: "foundation-ai-map",
    durationMin: 42,
    xp: 140,
    title: {
      ru: "База с нуля: какие бывают AI и зачем они нужны",
      en: "AI from zero: model types and practical use",
    },
    summary: {
      ru: "Текстовые, графические, видео и голосовые AI: где какой инструмент применять.",
      en: "Text, image, video, and voice AI: where each tool fits best.",
    },
    tags: {
      industries: ["all"],
      roles: ["all"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["productivity", "quality", "training"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["kids", "teens", "young", "adults"],
    },
    sections: {
      ru: [
        "AI-инструменты делятся по типу задачи: текст (написание и анализ), изображения (дизайн), видео (сцены и ролики), аудио/речь (озвучка и транскрибация).",
        "Текстовые модели лучше всего решают: объяснение тем, резюме документов, идеи, сценарии, письма, код и анализ таблиц.",
        "Графические модели нужны, когда важны визуальные стили: постеры, карточки товара, иллюстрации, обложки, презентации.",
        "Видео-модели полезны для коротких роликов: рекламные клипы, обучающие вставки, социальные сети, продуктовые демо.",
        "Голосовые модели применяются для TTS и STT: озвучка уроков, аудиоверсии материалов, расшифровка интервью и звонков.",
        "Универсальный принцип выбора: сначала цель, затем формат результата, затем ограничения по качеству, времени и стоимости.",
        "Практика: возьми одну реальную задачу и определи, какой тип AI даст максимальную пользу быстрее всего.",
        "Итог модуля: ты понимаешь карту AI-инструментов и умеешь осознанно выбирать тип модели под задачу.",
      ],
      en: [
        "AI tools are grouped by task type: text, image, video, and speech.",
        "Text models are strongest for explanation, summarization, drafting, brainstorming, coding, and analysis.",
        "Image models are used for design-heavy outcomes: banners, product cards, covers, and visual concepts.",
        "Video models fit short clips: ad snippets, explainer scenes, social content, and product teasers.",
        "Voice models cover speech-to-text and text-to-speech workflows.",
        "Selection rule: define goal first, then output format, then limits for quality, speed, and cost.",
        "Practice: take one real task and map it to one model type with clear reasoning.",
        "Outcome: you can choose the right AI modality for the right task with confidence.",
      ],
    },
  },
  {
    id: "foundation-account-setup",
    durationMin: 28,
    xp: 118,
    title: {
      ru: "Первые шаги: регистрация, доступы и базовая настройка AI-сервисов",
      en: "First setup: signup, access, and core AI service settings",
    },
    summary: {
      ru: "Как без стресса запустить первый AI-сервис: учетка, безопасность, тариф и первый рабочий запрос.",
      en: "How to launch your first AI service safely: account, security, billing, and first practical prompt.",
    },
    tags: {
      industries: ["all"],
      roles: ["all"],
      levels: ["beginner", "intermediate"],
      goals: ["productivity", "training", "quality"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Стартуй с выбора 1-2 AI-сервисов под задачу: текст, изображение, видео или код. Не пытайся сразу охватить все.",
        "Создай отдельную рабочую почту для AI-сервисов, чтобы не смешивать личные и рабочие доступы.",
        "После регистрации сразу включи базовую защиту: сложный пароль и двухфакторную авторизацию.",
        "Проверь тариф: бесплатный, trial или платный. Зафиксируй лимиты, чтобы контролировать расходы.",
        "Сохрани чеклист доступа: где логин, кто владелец аккаунта, как восстановить вход, кто отвечает за оплату.",
        "Первый запуск: создай новый чат и отправь простой структурный запрос по формуле роль -> цель -> формат.",
        "Сделай короткий результат и проверь его по двум критериям: полезность и точность.",
        "Итог: аккаунт настроен, доступы контролируются, есть первый рабочий AI-результат.",
      ],
      en: [
        "Start by selecting 1-2 AI services for your immediate tasks: text, image, video, or code.",
        "Create a dedicated work email for AI tools to avoid mixing personal and business access.",
        "After signup, enable baseline security: strong password and two-factor authentication.",
        "Review the plan type: free, trial, or paid. Record limits to control spending.",
        "Keep a simple access checklist: owner, recovery flow, billing responsibility, and usage policy.",
        "First run: open a new chat and send a structured prompt with role, goal, and output format.",
        "Generate a short output and review it by two criteria: usefulness and accuracy.",
        "Outcome: account is configured, access is controlled, and your first practical AI result is ready.",
      ],
    },
  },
  {
    id: "foundation-prompt-blueprint",
    durationMin: 46,
    xp: 155,
    title: {
      ru: "Промпт по частям: простая формула сильного запроса",
      en: "Prompt by parts: a simple structure for strong prompts",
    },
    summary: {
      ru: "Пошаговый шаблон: роль, цель, контекст, ограничения, формат, критерии качества.",
      en: "Step-by-step template: role, goal, context, constraints, output, quality criteria.",
    },
    tags: {
      industries: ["all"],
      roles: ["all"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["productivity", "quality", "content", "sales", "training"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Слабый промпт: «Сделай хорошо». Сильный промпт: «Ты маркетолог B2B. Сделай 3 варианта оффера для HR-сервиса, формат: таблица, тон: деловой, длина до 120 слов».",
        "Часть 1 — Роль: кем модель должна быть (аналитик, преподаватель, редактор, разработчик).",
        "Часть 2 — Цель: какой конкретный результат нужен (не процесс, а финальный артефакт).",
        "Часть 3 — Контекст: входные данные, аудитория, ниша, текущие ограничения проекта.",
        "Часть 4 — Ограничения: объем, стиль, запрещенные темы, правки по тону, дедлайн.",
        "Часть 5 — Формат: список, таблица, JSON, чеклист, структура презентации, план урока.",
        "Часть 6 — Критерии качества: что считается хорошим ответом, по каким признакам проверяем.",
        "Шаблон для копирования: «Роль: ... Цель: ... Контекст: ... Ограничения: ... Формат: ... Критерии качества: ...».",
        "Практика: переформулируй 2 своих слабых запроса в сильные и сравни результаты.",
      ],
      en: [
        "Weak prompt: 'Do it well'. Strong prompt: role + goal + context + constraints + format + quality criteria.",
        "Part 1 — Role: define who the model should act as.",
        "Part 2 — Goal: define exact final deliverable.",
        "Part 3 — Context: include inputs, audience, domain, and constraints.",
        "Part 4 — Constraints: limits for length, style, compliance, and scope.",
        "Part 5 — Output format: table, checklist, JSON, outline, script, etc.",
        "Part 6 — Quality criteria: define how output will be judged.",
        "Copy template: Role / Goal / Context / Constraints / Output / Quality criteria.",
        "Practice: rewrite two weak prompts into structured prompts and compare quality.",
      ],
    },
  },
  {
    id: "foundation-prompt-iteration",
    durationMin: 38,
    xp: 132,
    title: {
      ru: "Как улучшать ответ: итерации, уточнения и отладка промпта",
      en: "How to improve outputs: iteration and prompt debugging",
    },
    summary: {
      ru: "Метод 3 итераций: диагностика ошибки, уточнение запроса, повторная проверка.",
      en: "Three-iteration loop: diagnose, refine, validate.",
    },
    tags: {
      industries: ["all"],
      roles: ["all"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["quality", "productivity", "automation"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Итерация 1: получи черновой ответ и найди главную проблему (нет структуры, нет точности, не тот тон).",
        "Итерация 2: добавь конкретику в промпт: «Сократи до 5 пунктов», «Дай таблицу», «Укажи риски отдельно».",
        "Итерация 3: попроси самооценку: «Проверь свой ответ по критериям качества и отметь слабые места».",
        "При неточности фактов: «Покажи, какие утверждения требуют проверки источником».",
        "При слабой применимости: «Переделай ответ под мой кейс: [контекст], [аудитория], [цель]».",
        "При слишком общем ответе: «Добавь конкретные примеры и шаги внедрения по дням».",
        "При перегрузе: «Сделай две версии: короткая (до 120 слов) и рабочая (с чеклистом)».",
        "Итог: качество ответа растет не одним идеальным запросом, а грамотной итерацией.",
      ],
      en: [
        "Iteration 1: generate draft and identify primary failure mode.",
        "Iteration 2: tighten prompt with concrete constraints and format rules.",
        "Iteration 3: ask model to self-check against explicit quality criteria.",
        "For factual uncertainty: ask which claims require source verification.",
        "For low applicability: reframe with your real use-case context.",
        "For generic output: request concrete examples and day-by-day actions.",
        "For verbosity: request concise and operational versions.",
        "Outcome: quality comes from structured iteration, not one magic prompt.",
      ],
    },
  },
  {
    id: "foundation-data-safety",
    durationMin: 34,
    xp: 128,
    title: {
      ru: "Безопасность данных: что можно и нельзя отправлять в AI",
      en: "Data safety: what to send and what not to send to AI",
    },
    summary: {
      ru: "Персональные данные, коммерческая тайна, пароли, юридически чувствительные документы.",
      en: "PII, trade secrets, credentials, and high-risk legal/medical data handling.",
    },
    tags: {
      industries: ["all"],
      roles: ["all"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["quality", "training", "automation"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["kids", "teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Никогда не отправляй в AI: пароли, приватные ключи, номера карт, документы с персональными данными без политики компании.",
        "Перед отправкой данных применяй маскирование: имена, телефоны, e-mail, реквизиты заменяй на псевдонимы.",
        "Для работы с клиентскими данными используй принцип минимума: передавай только то, что реально нужно для задачи.",
        "Проверяй ограничения платформы: у разных AI-провайдеров разная политика хранения и модерации.",
        "Для детей и подростков нужен усиленный контроль контента и приватности, включая возрастные ограничения сервисов.",
        "В рабочих процессах вводи правило двойной проверки для важных решений: AI + человек-эксперт.",
        "Если ответ AI выглядит уверенно, это не гарантия истины. Всегда перепроверяй факты перед публикацией.",
        "Итог: безопасная работа с AI — это не запрет, а дисциплина данных, проверка и контроль риска.",
      ],
      en: [
        "Never send passwords, private keys, payment data, or raw sensitive personal records.",
        "Apply masking before prompting: anonymize names, contacts, and identifiers.",
        "Use minimum necessary data principle for every request.",
        "Review provider policies because retention and safety behavior differ across platforms.",
        "For minors, apply stricter safety controls and age-appropriate guardrails.",
        "For high-stakes outcomes, use human review before execution.",
        "Confident output is not guaranteed truth; verify critical claims.",
        "Outcome: safe AI use is disciplined data handling plus verification loops.",
      ],
    },
  },
  {
    id: "foundation-image-prompting",
    durationMin: 36,
    xp: 136,
    title: {
      ru: "Генерация изображений с нуля: как писать визуальный промпт",
      en: "Image prompting from zero: how to build visual prompts",
    },
    summary: {
      ru: "Цель изображения, стиль, композиция, свет, ракурс, негативные ограничения.",
      en: "Image objective, style, composition, lighting, camera angle, negative constraints.",
    },
    tags: {
      industries: ["all"],
      roles: ["marketer", "manager", "owner", "specialist", "teacher"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["content", "quality", "sales"],
      formats: ["text", "hybrid"],
      ageGroups: ["teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Сначала зафиксируй назначение: рекламный баннер, карточка товара, иллюстрация для урока или презентации.",
        "Добавь стиль: фотореализм, 3D, flat, акварель, cinematic, minimal.",
        "Укажи композицию: крупный план, общий план, объект в центре, правило третей, фон/передний план.",
        "Определи свет и цвет: мягкий дневной свет, контрастный неон, теплый тон, фирменная палитра.",
        "Добавь ограничения: «без логотипов конкурентов», «без текста», «без искаженных рук/лиц».",
        "Если нужны серии изображений, фиксируй постоянные параметры (персонаж, палитра, стиль) для консистентности.",
        "Для коммерческого использования проверяй соответствие бренд-гайду и авторским ограничениям.",
        "Практика: сгенерируй 3 варианта, выбери лучший и улучши вторым промптом по конкретным правкам.",
      ],
      en: [
        "Start with purpose: ad banner, product card, lesson visual, or presentation image.",
        "Define style clearly: photoreal, cinematic, flat, watercolor, 3D, minimal.",
        "Specify composition and camera framing.",
        "Set lighting and palette constraints for consistency.",
        "Use negative constraints to prevent unwanted artifacts.",
        "For series output, lock reusable parameters for visual consistency.",
        "Validate brand and copyright constraints before publishing.",
        "Practice: generate three variants and refine the best one with targeted edits.",
      ],
    },
  },
  {
    id: "foundation-video-prompting",
    durationMin: 41,
    xp: 148,
    title: {
      ru: "Видео с AI: структура сценария, сцены и монтажная логика",
      en: "AI video basics: scripting, scene structure, and pacing",
    },
    summary: {
      ru: "Промпт для видео по сценам: действие, камера, звук, длительность, финальный CTA.",
      en: "Scene-by-scene prompting: action, camera, audio, timing, final CTA.",
    },
    tags: {
      industries: ["all"],
      roles: ["marketer", "manager", "owner", "teacher", "specialist"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["content", "sales", "training"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Для короткого ролика используй структуру: хук (0-3 сек) -> демонстрация -> выгода -> призыв к действию.",
        "Промпт для каждой сцены должен содержать: что в кадре, что делает объект, как движется камера.",
        "Добавляй параметры атмосферы: освещение, темп, стиль, эмоциональный тон.",
        "Если платформа поддерживает звук, опиши характер аудио: спокойный, энергичный, ambient, без авторской музыки.",
        "Ограничения важны: длительность сцены, недопустимые элементы, требования безопасности.",
        "Видео должно быть понятным без контекста: зритель за 3 секунды должен понять тему.",
        "После генерации сделай редакторский проход: убрать лишнее, усилить CTA, выровнять динамику.",
        "Практика: создай сценарий из 5 сцен и протестируй две версии хука.",
      ],
      en: [
        "Use a compact structure: hook -> demonstration -> value -> CTA.",
        "For each scene define subject, action, and camera movement.",
        "Add style controls: lighting, pacing, mood, and visual tone.",
        "If audio is supported, describe intended sound profile clearly.",
        "Include constraints for duration and prohibited elements.",
        "Viewer should understand core message in first seconds.",
        "Run post-generation edit pass for clarity and pacing.",
        "Practice: create a 5-scene script and test two hook variants.",
      ],
    },
  },
  {
    id: "foundation-code-with-ai",
    durationMin: 52,
    xp: 176,
    title: {
      ru: "Программирование с AI: от идеи до простого веб-сайта",
      en: "Coding with AI: from idea to a simple website",
    },
    summary: {
      ru: "Пошаговый сценарий для новичка: ТЗ, код, запуск, отладка и улучшение.",
      en: "Beginner workflow: spec, code generation, run, debug, refine.",
    },
    tags: {
      industries: ["all"],
      roles: ["specialist", "manager", "owner", "teacher", "analyst", "marketer"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["automation", "productivity", "training", "content"],
      formats: ["text", "hybrid"],
      ageGroups: ["teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Шаг 1: сформулируй задачу как мини-ТЗ: «Нужен одностраничный сайт-визитка с блоками: hero, услуги, контакты».",
        "Шаг 2: попроси AI дать структуру файлов и минимальный стек (например, HTML/CSS/JS или Next.js).",
        "Шаг 3: генерируй код частями: сначала каркас страницы, затем стили, затем интерактив.",
        "Шаг 4: запускай локально и фиксируй ошибки. В запросе к AI давай точный текст ошибки и участок кода.",
        "Шаг 5: проси объяснение каждого блока кода простым языком, если что-то непонятно.",
        "Шаг 6: добавляй критерии качества: адаптивность, доступность, скорость загрузки, чистая структура.",
        "Шаг 7: внедри цикл улучшений: «проверь код на уязвимости, дубли и UX-проблемы».",
        "Итог: AI не заменяет разработчика, но резко ускоряет обучение и итерации при правильной постановке задачи.",
      ],
      en: [
        "Step 1: write a mini-spec with clear sections and expected output.",
        "Step 2: ask AI for file structure and minimal tech stack.",
        "Step 3: generate code incrementally: layout -> styles -> interactions.",
        "Step 4: run locally and feed exact error messages back to AI.",
        "Step 5: ask for plain-language explanation of unclear code blocks.",
        "Step 6: enforce quality criteria: responsiveness, accessibility, performance.",
        "Step 7: run review loop for bugs, duplication, and UX quality.",
        "Outcome: AI accelerates learning and delivery when task framing is correct.",
      ],
    },
  },
  {
    id: "core-ai-literacy",
    durationMin: 34,
    xp: 118,
    title: {
      ru: "AI-грамотность и безопасный старт",
      en: "AI literacy and a safe start",
    },
    summary: {
      ru: "Что умеет AI, где ошибается и как не принимать галлюцинации за факты.",
      en: "How AI helps, where it fails, and how to avoid trusting hallucinations.",
    },
    tags: {
      industries: ["all"],
      roles: ["all"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["productivity", "quality", "training"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["kids", "teens", "young", "adults"],
    },
    sections: {
      ru: [
        "AI не знает истину, он предсказывает вероятный следующий ответ. Поэтому факты и цифры из важного контента всегда проверяются отдельно.",
        "Главный риск новичка: путать уверенный тон модели с достоверностью. Уверенность формулировки не равна корректности.",
        "Базовый протокол безопасности: не отправляй пароли, ключи, персональные данные, неразрешенные документы и внутренние финансовые данные.",
        "Разделяй задачи на low-risk и high-risk. Для high-risk всегда добавляй экспертную проверку человеком перед публикацией или отправкой клиенту.",
        "Рабочий цикл: цель -> контекст -> ограничения -> формат -> критерии качества -> проверка фактов.",
        "Проси модель явно отметить, где она предполагает, а где опирается на предоставленные данные.",
        "Фиксируй удачные промпты и результаты в личной базе шаблонов, чтобы не начинать каждый раз с нуля.",
        "Итог: AI-грамотность означает дисциплину проверки, безопасности и повторяемого рабочего процесса.",
      ],
      en: [
        "AI predicts likely outputs, not objective truth, so critical facts require external verification.",
        "Main beginner mistake: confusing confident wording with reliable information.",
        "Never send credentials, private keys, unmasked personal data, or restricted internal documents.",
        "Split tasks into low-risk and high-risk; high-risk outputs require human review before use.",
        "Use a repeatable flow: goal -> context -> constraints -> format -> quality criteria -> verification.",
        "Ask the model to label assumptions versus confirmed data.",
        "Store successful prompts in a reusable template library.",
        "Outcome: AI literacy is operational discipline, not one-time prompting tricks.",
      ],
    },
  },
  {
    id: "core-prompt-framework",
    durationMin: 40,
    xp: 140,
    title: {
      ru: "Промпты без воды: шаблон, который работает",
      en: "Prompting without fluff: a framework that works",
    },
    summary: {
      ru: "Универсальная конструкция запроса для текста, изображений и видео.",
      en: "A universal prompt structure for text, image, and video tasks.",
    },
    tags: {
      industries: ["all"],
      roles: ["all"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["productivity", "quality", "content", "sales"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Структура сильного промпта: роль, цель, контекст, ограничения, формат, критерии качества.",
        "Роль задает угол зрения: эксперт, преподаватель, редактор, аналитик, разработчик. Это напрямую влияет на стиль ответа.",
        "Цель должна быть конкретной: «сделай 3 оффера в таблице», а не «помоги с маркетингом».",
        "Контекст включает аудиторию, продукт, ограничения по срокам и то, что уже пробовали раньше.",
        "Ограничения делают ответ применимым: объем, запрещенные темы, тон, требуемый уровень точности.",
        "Формат задает готовый артефакт: чеклист, таблица, JSON, план урока, сценарий, ТЗ.",
        "Критерии качества нужны заранее: чем измеряем успех (ясность, точность, применимость, отсутствие воды).",
        "Быстрый шаблон: «Роль: ... Цель: ... Контекст: ... Ограничения: ... Формат: ... Критерии: ...».",
        "Практика: возьми 1 рабочую задачу и прогони 2 версии промпта: без структуры и со структурой. Сравни качество.",
      ],
      en: [
        "Reliable prompts use six parts: role, goal, context, constraints, output format, and quality criteria.",
        "Role sets perspective and response style for the model.",
        "Goals must be concrete deliverables, not broad wishes.",
        "Context should include audience, domain, and existing constraints.",
        "Constraints make output executable in real workflows.",
        "Format defines the final artifact shape: table, checklist, JSON, outline, script.",
        "Quality criteria provide objective evaluation rules.",
        "Reusable template: Role / Goal / Context / Constraints / Output / Quality criteria.",
        "Practice: compare unstructured versus structured prompt quality on one real task.",
      ],
    },
  },
  {
    id: "core-fact-check",
    durationMin: 30,
    xp: 112,
    title: {
      ru: "Проверка фактов и анти-ошибки",
      en: "Fact-checking and error control",
    },
    summary: {
      ru: "Контрольный чеклист перед отправкой результата клиенту или руководителю.",
      en: "A quality checklist before sending output to clients or leadership.",
    },
    tags: {
      industries: ["all"],
      roles: ["all"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["quality", "training"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["kids", "teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Факт-чекинг начинается не после ответа, а до запроса: определи, что в задаче критично и не может быть ошибочным.",
        "Проверяй отдельно: цифры, даты, имена, цитаты, правовые формулировки, медицинские и финансовые утверждения.",
        "Попроси модель выделить спорные места: «Укажи, какие пункты требуют проверки источниками».",
        "Второй контур контроля: первоисточник или профильный эксперт, если результат влияет на деньги, репутацию или безопасность.",
        "Разделяй утверждения на три группы: подтверждено данными, предположение, мнение/интерпретация.",
        "Используй правило двух независимых подтверждений для ключевых фактов перед публикацией.",
        "Перед отправкой клиенту добавляй короткий чеклист в конце ответа: что проверено и что требует подтверждения.",
        "Итог: качественная работа с AI невозможна без встроенного процесса проверки достоверности.",
      ],
      en: [
        "Fact-checking starts before prompting by defining high-risk claims.",
        "Verify numbers, dates, names, quotes, legal wording, and compliance-sensitive statements.",
        "Ask the model to flag claims that need source validation.",
        "For high-stakes outputs, enforce second-layer review with primary sources or experts.",
        "Label every key claim as confirmed data, assumption, or interpretation.",
        "Use a two-source rule for critical facts before publication.",
        "Attach a short verification checklist to every final deliverable.",
        "Outcome: trustworthy AI use requires explicit verification operations.",
      ],
    },
  },
  {
    id: "age-kids-safe-start",
    durationMin: 28,
    xp: 105,
    title: {
      ru: "8-12 лет: безопасный старт и творческие задачи с AI",
      en: "Ages 8-12: safe AI start and creative tasks",
    },
    summary: {
      ru: "Простым языком: что такое AI, как задавать вопросы и что никогда нельзя отправлять.",
      en: "Simple language: what AI is, how to ask questions, and what must never be shared.",
    },
    tags: {
      industries: ["all"],
      roles: ["all"],
      levels: ["beginner", "intermediate"],
      goals: ["training", "quality", "productivity"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["kids"],
      learnerTypes: ["individual", "company"],
    },
    sections: {
      ru: [
        "AI - это помощник, который умеет объяснять, придумывать и подсказывать, но не всегда говорит точно.",
        "Главное правило: никогда не отправляй личные данные - адрес, номер телефона, пароли и данные банковской карты.",
        "Чтобы получить хороший ответ, задавай вопрос по шагам: кто ты, что хочешь сделать, какой результат нужен.",
        "Пример: «Объясни тему дробей для ученика 4 класса на 3 простых примерах».",
        "Если ответ сложный, проси упростить: «Объясни еще проще и добавь 2 задания для тренировки».",
        "Если ответ непонятный или странный, спроси заново другими словами и сравни два варианта.",
        "Работай вместе со взрослым, если задача связана с деньгами, медициной, документами или публикацией в интернете.",
        "Итог: ты умеешь безопасно использовать AI для учебы, творчества и тренировки мышления.",
      ],
      en: [
        "AI is a helper for ideas and explanations, but it can be wrong.",
        "Never share personal data such as address, phone, passwords, or card details.",
        "Use simple prompt structure: who you are, what you need, and expected result.",
        "Example: explain fractions for grade 4 with three easy examples.",
        "If output is hard, ask to simplify and add practice tasks.",
        "If output is unclear, re-ask and compare two versions.",
        "For finance, legal, or medical tasks, use adult supervision.",
        "Outcome: safe and practical AI use for learning and creativity.",
      ],
    },
  },
  {
    id: "age-teens-study-projects",
    durationMin: 34,
    xp: 122,
    title: {
      ru: "13-17 лет: учеба, проекты и честная работа с AI",
      en: "Ages 13-17: study workflows, projects, and responsible AI use",
    },
    summary: {
      ru: "Как использовать AI для подготовки, не теряя самостоятельность и качество знаний.",
      en: "Use AI for better study outcomes without losing independent thinking.",
    },
    tags: {
      industries: ["education", "all"],
      roles: ["student", "specialist", "teacher", "all"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["training", "quality", "productivity", "content"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["teens"],
      learnerTypes: ["individual", "company"],
    },
    sections: {
      ru: [
        "AI ускоряет учебу, если использовать его как наставника, а не как способ копировать готовые ответы.",
        "Запрос для подготовки к теме: «Объясни тему ... по шагам, затем задай мне 5 проверочных вопросов».",
        "Для проектов используй цикл: идея -> план -> черновик -> проверка источников -> финальная версия.",
        "Проси AI указывать спорные места и где нужны источники, чтобы не допускать ошибок в фактах.",
        "Для презентации попроси структуру слайдов, но примеры, выводы и аргументы формулируй сам.",
        "Хорошая практика: после ответа AI напиши своими словами короткое резюме темы.",
        "Не отправляй чужие персональные данные, экзаменационные материалы и закрытые документы.",
        "Итог: AI помогает учиться глубже, когда ты сохраняешь критическое мышление и личный вклад.",
      ],
      en: [
        "Use AI as a tutor, not as a copy-paste answer machine.",
        "Prompt format: explain topic step by step, then ask five check questions.",
        "Project loop: idea -> outline -> draft -> source check -> final.",
        "Ask AI to mark claims that need verification.",
        "Use AI for slide structure but keep your own reasoning and conclusions.",
        "After each output, write a short summary in your own words.",
        "Never share other people’s personal data or restricted documents.",
        "Outcome: stronger learning with AI plus critical thinking.",
      ],
    },
  },
  {
    id: "age-young-career-boost",
    durationMin: 36,
    xp: 126,
    title: {
      ru: "18-29 лет: карьера, фриланс и запуск своих AI-процессов",
      en: "Ages 18-29: career growth, freelancing, and AI workflows",
    },
    summary: {
      ru: "Как применять AI в работе: задачи, портфолио, коммуникации и рост дохода.",
      en: "Apply AI to work tasks, portfolio building, communication, and income growth.",
    },
    tags: {
      industries: ["all"],
      roles: ["specialist", "manager", "marketer", "analyst", "sales", "teacher"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["productivity", "quality", "content", "sales", "automation"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["young"],
      learnerTypes: ["individual", "company"],
    },
    sections: {
      ru: [
        "Сфокусируйся на задачах с быстрым эффектом: письма, контент, анализ, подготовка встреч, резюме документов.",
        "Собери персональный стек из 3-5 инструментов: текст, изображение, видео, автоматизация и заметки.",
        "Для каждой роли сделай библиотеку промптов: продажи, маркетинг, аналитика, обучение, поддержка.",
        "Рабочий стандарт: черновик от AI -> редактура -> факт-чекинг -> финальный материал.",
        "Используй AI для портфолио: кейсы до/после, описание процесса, измеримый результат.",
        "При фрилансе фиксируй в ТЗ формат, объем и критерии приемки, чтобы AI-результат был применим сразу.",
        "Повышай ставку через скорость и качество: считай экономию времени на каждой задаче.",
        "Итог: AI становится рычагом карьерного роста, когда построен личный системный процесс.",
      ],
      en: [
        "Start with high-impact tasks: writing, analysis, prep, and content production.",
        "Build a compact tool stack for text, image, video, and automation.",
        "Create role-specific prompt libraries for repeatable tasks.",
        "Use a quality pipeline: draft -> edit -> verify -> final.",
        "Turn outputs into portfolio case studies with measurable outcomes.",
        "In freelancing, define strict acceptance criteria in advance.",
        "Track time savings and quality gains for pricing growth.",
        "Outcome: AI becomes a career multiplier through repeatable workflows.",
      ],
    },
  },
  {
    id: "age-adults-workflow-adoption",
    durationMin: 34,
    xp: 118,
    title: {
      ru: "30+ лет: внедрение AI в ежедневную работу без хаоса",
      en: "Ages 30+: structured AI adoption for daily work",
    },
    summary: {
      ru: "Как внедрять AI в процессы, не теряя контроль, качество и безопасность.",
      en: "Integrate AI into routines while preserving control, quality, and safety.",
    },
    tags: {
      industries: ["all"],
      roles: ["owner", "manager", "specialist", "analyst", "teacher"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["productivity", "quality", "automation", "training"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["adults"],
      learnerTypes: ["individual", "company"],
    },
    sections: {
      ru: [
        "Начни с карты процессов: где много повторяющихся задач, долгих согласований и ручной рутины.",
        "Определи 3 сценария на запуск: быстрые ответы, подготовка отчетов, генерация материалов для команды.",
        "Для каждого сценария назначь владельца, критерии качества и лимиты ответственности AI.",
        "Введи правило «человек подтверждает» для документов, где есть юридические, финансовые или репутационные риски.",
        "Сохраняй лучшие промпты в корпоративной библиотеке, чтобы команда работала по единому стандарту.",
        "Измеряй эффект через KPI: время цикла задачи, количество доработок, качество первого результата.",
        "Проводи еженедельный разбор: что автоматизировать дальше и где нужны дополнительные инструкции.",
        "Итог: зрелое внедрение AI строится на процессах, роли владельца и системе качества.",
      ],
      en: [
        "Start with process mapping to identify repetitive and slow manual workflows.",
        "Launch with three high-return scenarios and clear ownership.",
        "Define quality criteria and AI responsibility limits per workflow.",
        "Use mandatory human approval for legal, financial, or reputational risk outputs.",
        "Maintain a shared prompt library for consistency across team members.",
        "Measure impact via cycle time, rework rate, and first-pass quality.",
        "Run weekly reviews to decide what to automate next.",
        "Outcome: sustainable AI adoption requires process governance.",
      ],
    },
  },
  {
    id: "company-ai-rollout",
    durationMin: 44,
    xp: 158,
    title: {
      ru: "Пакет для компании: как внедрить AI в команду по шагам",
      en: "Company rollout: step-by-step AI implementation playbook",
    },
    summary: {
      ru: "Диагностика, пилот, политика использования, KPI и масштабирование на сотрудников.",
      en: "Diagnostic, pilot, policy, KPI tracking, and team-wide scale-up.",
    },
    tags: {
      industries: ["all"],
      roles: ["owner", "manager", "hr", "analyst"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["training", "automation", "quality", "productivity"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["young", "adults"],
      learnerTypes: ["company"],
    },
    sections: {
      ru: [
        "Шаг 1 - диагностика: выбери 5-7 процессов, где AI даст максимальную пользу за 2-4 недели.",
        "Шаг 2 - пилот: назначь ответственную мини-команду и зафиксируй измеримые цели внедрения.",
        "Шаг 3 - стандарты: утверди политику данных, список разрешенных инструментов и шаблоны промптов.",
        "Шаг 4 - обучение: запусти персональные треки по роли и отрасли, а не единый курс для всех.",
        "Шаг 5 - контроль качества: введи правило проверки критичных результатов человеком.",
        "Шаг 6 - экономика: считай ROI по экономии времени, сокращению ошибок и росту конверсии.",
        "Шаг 7 - масштабирование: расширяй сценарии только после успешных пилотов и понятных метрик.",
        "Шаг 8 - поддержка: обновляй базу промптов и проводи регулярные внутренние разборы кейсов.",
        "Итог: компания получает управляемое внедрение AI, а не хаотичное использование инструментов.",
      ],
      en: [
        "Step 1: prioritize 5-7 workflows with highest near-term AI impact.",
        "Step 2: run a pilot with clear ownership and measurable targets.",
        "Step 3: approve data policy, allowed tools, and prompt standards.",
        "Step 4: train by role and industry instead of one generic course.",
        "Step 5: enforce human review for critical outputs.",
        "Step 6: calculate ROI from time savings, quality gains, and conversion impact.",
        "Step 7: scale only validated pilot workflows with clear metrics.",
        "Step 8: maintain shared prompt knowledge base and case reviews.",
        "Outcome: controlled AI adoption with governance and measurable business value.",
      ],
    },
  },
  {
    id: "industry-retail-content",
    durationMin: 40,
    xp: 138,
    title: {
      ru: "AI в ритейле: карточки товара и описания, которые продают",
      en: "AI in retail: product cards and descriptions that sell",
    },
    summary: {
      ru: "Быстрая генерация карточек, SEO-описаний и сценариев акций.",
      en: "Fast generation of product cards, SEO descriptions, and promo ideas.",
    },
    tags: {
      industries: ["retail"],
      roles: ["owner", "manager", "marketer", "sales", "specialist"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["content", "sales", "productivity"],
      formats: ["text", "hybrid"],
      ageGroups: ["young", "adults"],
    },
    sections: {
      ru: [
        "Начни с карточки эталона: характеристики товара, портрет покупателя, ключевые боли и аргументы покупки.",
        "Промпт для карточки: «Сделай 3 версии описания товара: короткая, стандартная, SEO. Добавь блок FAQ и возражения».",
        "Собирай заголовки пакетно: 10 вариантов под разные углы ценности (цена, удобство, надежность, скорость доставки).",
        "Разделяй вывод для каналов: маркетплейс, сайт, соцсети, рекламные объявления требуют разного формата текста.",
        "Попроси AI сформировать таблицу A/B теста: гипотеза, метрика, срок теста, порог принятия решения.",
        "Добавь модуль пост-аналитики: какие формулировки повышают CTR и конверсию в корзину.",
        "Перед публикацией проверь юридическую корректность обещаний (сроки, гарантии, характеристики).",
        "Итог: у тебя готовый конвейер создания контента для товаров с контролем результата в цифрах.",
      ],
      en: [
        "Start from a golden product brief: specs, audience pains, benefits, and objections.",
        "Use a prompt to generate short, standard, and SEO product copy variants.",
        "Generate headline batches across different value angles for testing.",
        "Create channel-specific outputs for marketplace, website, and ads.",
        "Ask AI for an A/B test table with metrics and decision thresholds.",
        "Review what phrasing drives better CTR and add-to-cart conversion.",
        "Validate legal accuracy of claims before publishing.",
        "Outcome: repeatable retail content pipeline with measurable impact.",
      ],
    },
  },
  {
    id: "industry-services-support",
    durationMin: 38,
    xp: 132,
    title: {
      ru: "AI в сервисе: быстрые ответы клиентам без потери качества",
      en: "AI for services: fast client replies without losing quality",
    },
    summary: {
      ru: "Сценарии для поддержки, повторных продаж и конфликтных обращений.",
      en: "Templates for support, upsell replies, and conflict management.",
    },
    tags: {
      industries: ["services"],
      roles: ["manager", "sales", "specialist", "owner"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["productivity", "quality", "sales"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["young", "adults"],
    },
    sections: {
      ru: [
        "Построй матрицу диалогов: первый контакт, уточнение задачи, согласование цены, работа с возражениями, эскалация.",
        "Для каждого сценария зафиксируй целевой тон и цель ответа: успокоить, уточнить, закрыть на следующий шаг.",
        "Промпт-шаблон: «Сгенерируй 3 ответа: деловой, эмпатичный, краткий. Добавь версию для голосового сообщения».",
        "Попроси AI выделять риски в диалоге: конфликт, неполные данные, ожидания клиента, которые не подтверждены.",
        "Создай сценарии допродаж: когда и как предлагать дополнительную услугу без давления.",
        "Введи правило качества: ответ должен быть понятным, коротким и содержать конкретный следующий шаг.",
        "Отслеживай метрики: скорость первого ответа, процент повторных обращений, конверсия в оплату.",
        "Итог: AI помогает ускорить поддержку и продажи без потери сервиса и качества коммуникации.",
      ],
      en: [
        "Build conversation matrices for contact, clarification, pricing, objections, and escalation.",
        "Define target tone and response objective per scenario.",
        "Use a prompt template for business, empathetic, and concise response variants.",
        "Ask AI to flag risks such as conflict or missing requirements.",
        "Generate non-pushy upsell scripts for relevant moments.",
        "Set quality rule: clear, concise, with one explicit next step.",
        "Track first-response time, repeat tickets, and paid conversion.",
        "Outcome: faster support and stronger service quality.",
      ],
    },
  },
  {
    id: "industry-education-tutor",
    durationMin: 44,
    xp: 152,
    title: {
      ru: "AI в обучении: персональные мини-уроки и проверка заданий",
      en: "AI in education: personalized micro-lessons and assignment checks",
    },
    summary: {
      ru: "Как объяснять сложные темы простым языком для разных возрастов.",
      en: "How to explain complex topics in a simple way for different age groups.",
    },
    tags: {
      industries: ["education"],
      roles: ["teacher", "manager", "specialist"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["training", "quality", "productivity"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["kids", "teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Строй урок через микрошаги: цель урока -> мини-объяснение -> пример -> практика -> обратная связь.",
        "Промпт наставника: «Объясни тему для [возраст], уровень [уровень], стиль [визуал/текст], добавь 2 примера и 3 задания».",
        "Запрашивай у AI две версии объяснения: очень простую и более академичную для постепенного роста уровня.",
        "Сначала формируй критерии оценки задания, затем генерируй само задание - это снижает субъективность проверки.",
        "Используй адаптивный режим: если ученик ошибся, AI должен дать подсказку, а не сразу правильный ответ.",
        "Для подростков добавляй проектные задания, для детей - игровые форматы и короткие блоки внимания.",
        "Собирай прогресс по навыкам: что освоено, где пробелы, какие темы повторить.",
        "Итог: AI превращается в персонального тьютора с контролируемым качеством обучения.",
      ],
      en: [
        "Build lessons as micro-steps: objective, explanation, example, practice, feedback.",
        "Use tutor prompt with age, level, style, and lesson goal context.",
        "Request simple and advanced explanations for progressive understanding.",
        "Define assessment criteria before generating tasks.",
        "Use adaptive feedback: hints first, answers later.",
        "Apply game-like short cycles for kids and project mode for teens.",
        "Track skill-level progress and weak points.",
        "Outcome: AI-powered tutoring with measurable learning quality.",
      ],
    },
  },
  {
    id: "industry-marketing-campaigns",
    durationMin: 46,
    xp: 160,
    title: {
      ru: "AI в маркетинге: контент-поток и рекламные кампании",
      en: "AI in marketing: content flow and ad campaigns",
    },
    summary: {
      ru: "Календарь контента, сегменты аудиторий, офферы и тест гипотез.",
      en: "Content calendar, audience segments, offers, and hypothesis testing.",
    },
    tags: {
      industries: ["marketing", "retail", "services"],
      roles: ["marketer", "manager", "owner", "sales"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["content", "sales", "automation"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["young", "adults"],
    },
    sections: {
      ru: [
        "Работай от стратегии: сегменты аудитории, болевые точки, обещание ценности, канал коммуникации.",
        "Промпт для оффера: «Дай 10 вариантов оффера под 3 сегмента и 4 канала, разный тон и длина».",
        "Разделяй контент по воронке: охват, интерес, доверие, действие, удержание.",
        "Запрашивай у AI календарь контента на 2 недели с привязкой к KPI каждой публикации.",
        "Генерируй креативы пакетами: заголовок, текст, визуальная идея, CTA, гипотеза теста.",
        "Попроси модель прогнозировать риски: выгорание аудитории, повторяемость креативов, слабый оффер.",
        "Аналитика обязательна: CTR, CPC/CPL, конверсия, ROMI, LTV по сегментам.",
        "Итог: AI управляет скоростью маркетинга, но результат обеспечивается системой тестов и метрик.",
      ],
      en: [
        "Start from strategy: segment pains, value promise, and channel fit.",
        "Use prompts that generate multi-segment offer variants by channel.",
        "Map content to funnel stages from awareness to retention.",
        "Ask AI for a two-week content plan tied to KPIs.",
        "Generate full creative packs: headline, copy, visual idea, CTA, test hypothesis.",
        "Ask model to surface campaign risks and weak assumptions.",
        "Track CTR, CPL, conversion, ROMI, and segment-level LTV.",
        "Outcome: scalable AI marketing driven by experiments and metrics.",
      ],
    },
  },
  {
    id: "industry-hr-hiring",
    durationMin: 36,
    xp: 136,
    title: {
      ru: "AI в HR: вакансии, скрининг и адаптация сотрудников",
      en: "AI for HR: job descriptions, screening, and onboarding",
    },
    summary: {
      ru: "Автоматизация первичного подбора и сопровождения онбординга.",
      en: "Automating early recruitment steps and onboarding support.",
    },
    tags: {
      industries: ["hr", "operations", "services"],
      roles: ["hr", "manager", "owner"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["automation", "quality", "training"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["young", "adults"],
    },
    sections: {
      ru: [
        "Вакансию формируй через результат роли, а не список абстрактных требований.",
        "Промпт для JD: «Опиши роль через задачи на 30/60/90 дней и критерии успешности».",
        "Скрининг должен проверять реальные компетенции, а не только формальные признаки резюме.",
        "Сделай 3 шаблона интервью: структурированное, компетентностное, кейсовое.",
        "Попроси AI подготовить чеклист анти-дискриминационных формулировок в описании вакансии.",
        "Для онбординга генерируй персональный план адаптации на первые 2 недели с KPI.",
        "Отслеживай метрики HR-процесса: time-to-hire, качество найма, скорость адаптации.",
        "Итог: AI ускоряет найм и онбординг при соблюдении качества и этических стандартов.",
      ],
      en: [
        "Write job descriptions around outcomes, not generic requirement lists.",
        "Use prompt templates for 30/60/90-day expectations and success criteria.",
        "Design screening that tests real role competencies.",
        "Prepare structured, competency-based, and case interview variants.",
        "Ask AI to flag discriminatory or risky wording.",
        "Generate personalized two-week onboarding plans with KPIs.",
        "Track time-to-hire, quality-of-hire, and onboarding speed.",
        "Outcome: faster and better hiring with compliance-aware workflows.",
      ],
    },
  },
  {
    id: "industry-ops-automation",
    durationMin: 40,
    xp: 142,
    title: {
      ru: "AI в операциях: регламенты и автоматизация рутины",
      en: "AI in operations: SOPs and routine automation",
    },
    summary: {
      ru: "Как превратить повторяемые задачи в системный процесс.",
      en: "How to convert repetitive tasks into repeatable systems.",
    },
    tags: {
      industries: ["operations", "services", "retail"],
      roles: ["manager", "analyst", "owner", "specialist"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["automation", "productivity", "quality"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["young", "adults"],
    },
    sections: {
      ru: [
        "Сначала выбери процесс с повторяемой рутиной и явным узким местом по времени.",
        "Построй карту процесса: входные данные, шаги, ответственные, риски, SLA, метрика результата.",
        "Промпт для регламента: «Собери SOP по шагам, добавь контрольные точки и эскалацию ошибок».",
        "AI должен выдавать не только инструкцию, но и сценарии сбоя: что делать при отклонении процесса.",
        "Вводи частичную автоматизацию: сначала 1-2 этапа, затем масштабирование после проверки метрик.",
        "Фиксируй, где требуется ручной контроль качества и юридическое согласование.",
        "Измеряй эффект: время цикла, доля ошибок, доля задач без ручной доработки.",
        "Итог: автоматизация с AI работает только как управляемая система с владельцем процесса.",
      ],
      en: [
        "Pick repetitive workflows with clear time bottlenecks first.",
        "Map process inputs, steps, owners, risks, SLA, and success metrics.",
        "Use SOP prompts that include control points and escalation paths.",
        "Request failure scenarios and fallback handling logic from AI.",
        "Automate incrementally before full rollout.",
        "Keep explicit manual quality and legal control steps.",
        "Track cycle time, error rate, and no-rework completion ratio.",
        "Outcome: robust operations automation with clear ownership.",
      ],
    },
  },
  {
    id: "modality-image-gen",
    durationMin: 34,
    xp: 128,
    title: {
      ru: "Генерация изображений: от ТЗ до готового визуала",
      en: "Image generation: from brief to production visual",
    },
    summary: {
      ru: "Промпты для графики, контроль стиля и подготовка референсов.",
      en: "Image prompting, style consistency, and reference preparation.",
    },
    tags: {
      industries: ["all"],
      roles: ["marketer", "manager", "owner", "specialist", "teacher"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["content", "quality"],
      formats: ["text", "hybrid"],
      ageGroups: ["teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Начни с цели: где изображение будет использоваться - реклама, обучение, соцсети, сайт или презентация.",
        "Собери визуальный промпт из блоков: объект, действие, стиль, композиция, свет, палитра, формат кадра.",
        "Если нужна узнаваемость бренда, фиксируй фирменные цвета, тон, степень реалистичности и допустимые элементы.",
        "Добавляй negative prompt: что запрещено (артефакты, искажения лиц/рук, лишний текст, чужие логотипы).",
        "Генерируй серии: сначала 4-6 черновиков, затем дорабатывай лучший вариант точечными правками.",
        "Проверяй читаемость картинки в реальном размере: мобильный экран, карточка товара, баннер.",
        "Перед публикацией оцени юридические риски: авторские права, запрещенные образы, бренд-безопасность.",
        "Итог: ты умеешь получать стабильный визуальный результат, а не случайные красивые картинки.",
      ],
      en: [
        "Define exact image use-case before prompting.",
        "Build prompts with subject, action, style, composition, lighting, palette, and frame format.",
        "Lock brand constraints for consistency across outputs.",
        "Use negative prompts to suppress common visual artifacts.",
        "Generate draft batches first, then refine the best option.",
        "Validate readability in real placement sizes.",
        "Review copyright and policy risks before publishing.",
        "Outcome: repeatable image generation quality.",
      ],
    },
  },
  {
    id: "modality-video-gen",
    durationMin: 36,
    xp: 136,
    title: {
      ru: "AI-видео: сценарий, сториборд и быстрый продакшн",
      en: "AI video: scripting, storyboard, and fast production",
    },
    summary: {
      ru: "Как собрать короткое видео под задачу: обучение, реклама, объяснение.",
      en: "How to produce short videos for education, advertising, and explainers.",
    },
    tags: {
      industries: ["all"],
      roles: ["marketer", "manager", "owner", "teacher", "specialist"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["content", "sales", "training"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Собирай видео по структуре: хук -> проблема -> решение -> доказательство -> CTA.",
        "Разбей ролик на 5-7 сцен, каждая сцена решает один микровопрос аудитории.",
        "Промпт для сцены: что в кадре, действие, движение камеры, эмоция, длительность, текст/субтитр.",
        "Запрашивай у AI два варианта хука и CTA, чтобы тестировать конверсию.",
        "Если есть озвучка, задавай темп речи, тон диктора и стиль музыки без нарушения авторских прав.",
        "Своди все сцены в единый сториборд с таймингом и переходами до финальной генерации.",
        "После генерации проверь первые 3 секунды, динамику монтажа и ясность финального действия.",
        "Итог: ты создаешь не просто видео, а сценарно выверенный контент под конкретную бизнес-цель.",
      ],
      en: [
        "Use video structure: hook -> problem -> solution -> proof -> CTA.",
        "Split into 5-7 micro-scenes with one purpose each.",
        "Prompt each scene with visual action, camera movement, emotion, duration, and text.",
        "Generate two hook and CTA variants for conversion testing.",
        "Specify voice and music style with copyright-safe constraints.",
        "Build storyboard with timings and transitions before final generation.",
        "Validate first seconds, pacing, and CTA clarity after generation.",
        "Outcome: conversion-oriented AI video production.",
      ],
    },
  },
  {
    id: "business-payments-russia",
    durationMin: 28,
    xp: 104,
    title: {
      ru: "Оплата AI и SaaS в РФ: что учитывать команде",
      en: "Paying for AI and SaaS in Russia: practical setup",
    },
    summary: {
      ru: "Базовая схема оплаты, лимиты и комплаенс для компании.",
      en: "Practical payment setup, limits, and compliance basics for teams.",
    },
    tags: {
      industries: ["all"],
      roles: ["owner", "manager", "analyst", "hr"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["productivity", "quality", "training"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["young", "adults"],
      learnerTypes: ["company"],
    },
    sections: {
      ru: [
        "Сначала утверди реестр инструментов: какие AI-сервисы разрешены для текста, графики, видео и автоматизации.",
        "Назначь владельца бюджета и владельца доступа, чтобы платежи и аккаунты не были размыты по команде.",
        "Разделяй корпоративные и личные аккаунты сотрудников, чтобы избежать потери доступов при увольнении.",
        "Введи лимиты расходов по командам и ежемесячный отчет по использованию подписок.",
        "Настрой единый процесс оплаты через выбранного платежного провайдера и хранение закрывающих документов.",
        "Для новых сервисов проводи мини-аудит: условия использования, хранение данных, ограничения по контенту.",
        "Закрепи внутреннюю политику: что можно загружать в AI, что запрещено, кто отвечает за нарушения.",
        "Итог: платежи и доступ к AI становятся управляемой частью операционного процесса компании.",
      ],
      en: [
        "Approve a formal registry of allowed AI tools by use-case.",
        "Assign clear owners for budget and access governance.",
        "Separate personal and corporate accounts to reduce access risks.",
        "Set team budgets and monthly subscription usage reporting.",
        "Use a unified payment flow with proper accounting documents.",
        "Run lightweight policy and data checks before adopting new vendors.",
        "Document what data can and cannot be shared with AI tools.",
        "Outcome: predictable and compliant AI payment operations.",
      ],
    },
  },
  {
    id: "certification-capstone",
    durationMin: 48,
    xp: 188,
    title: {
      ru: "Финальная миссия: кейс, аттестация и сертификат",
      en: "Final mission: capstone, assessment, and certificate",
    },
    summary: {
      ru: "Игровая аттестация с реальной задачей из выбранной сферы.",
      en: "Game-style assessment based on a real role-specific task.",
    },
    tags: {
      industries: ["all"],
      roles: ["all"],
      levels: ["beginner", "intermediate", "advanced"],
      goals: ["quality", "training", "sales", "automation", "content"],
      formats: ["text", "voice", "hybrid"],
      ageGroups: ["kids", "teens", "young", "adults"],
    },
    sections: {
      ru: [
        "Финальный кейс строится из роли, отрасли и целей: ты работаешь с задачей, максимально близкой к реальной практике.",
        "Этап 1: сформулируй задачу и критерии успеха, которые можно измерить (время, качество, конверсия, точность).",
        "Этап 2: собери промпт по структуре (роль, цель, контекст, ограничения, формат, критерии качества).",
        "Этап 3: сделай минимум 2 итерации улучшения и объясни, почему финальная версия лучше стартовой.",
        "Этап 4: проведи факт-чекинг, отметь риски и ограничения применения результата.",
        "Этап 5: оформи финальный артефакт в рабочем формате: инструкция, текст, шаблон, сценарий или SOP.",
        "Система оценки: ясность задачи, качество промпта, практическая применимость, безопасность данных, качество проверки.",
        "После успешного прохождения открывается сертификат и персональный план развития на следующий уровень.",
      ],
      en: [
        "Capstone task is generated from role, industry, and goals.",
        "Step 1: define measurable success criteria for the task.",
        "Step 2: build a full structured prompt.",
        "Step 3: run at least two refinement iterations.",
        "Step 4: perform fact-check and risk labeling.",
        "Step 5: produce a final deliverable in operational format.",
        "Scoring covers clarity, prompt quality, utility, safety, and verification rigor.",
        "Completion unlocks certificate plus next-level learning plan.",
      ],
    },
  },
];
